// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACGPhm3Bb8PaukueXE8ap397qK16tEtfs',
    appId: '1:903443261144:web:5cef8f2631a686edcc59ad',
    messagingSenderId: '903443261144',
    projectId: 'dental-dentist',
    authDomain: 'dental-dentist.firebaseapp.com',
    storageBucket: 'dental-dentist.appspot.com',
    measurementId: 'G-0NYCW7458M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC40F8qx79fGYJvfp8l_Ged6lGJd3g9DA4',
    appId: '1:903443261144:android:2887167d233222f8cc59ad',
    messagingSenderId: '903443261144',
    projectId: 'dental-dentist',
    storageBucket: 'dental-dentist.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0fmgr-XX9Vo8kDvBx24k9lZnrTks2YXY',
    appId: '1:903443261144:ios:bf944389338cbd29cc59ad',
    messagingSenderId: '903443261144',
    projectId: 'dental-dentist',
    storageBucket: 'dental-dentist.appspot.com',
    iosBundleId: 'aralid.dental.dentalDentist',
  );
}
